apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-app
  labels:
    app: item-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-app
  template:
    metadata:
      labels:
        app: item-app
    spec:
      containers:
      - name: item-app
        image: docker.io/agus3rdyoga/item-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-db
  labels:
    app: item-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-db
  template:
    metadata:
      labels:
        app: item-db
    spec:
      containers:
      - name: item-db
        image: mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
