apiVersion: v1
kind: Service
metadata:
  name: item-app
  labels:
    app: item-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    #nodePort: 30007
  selector:
    app: item-app
---
apiVersion: v1
kind: Service
metadata:
  name: item-db
  labels:
    app: item-db
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
  #nodePort: 30007
  selector:
    app: item-db
