name: Karsajobs Build

on:
  push:
    branches: [ "karsajobs" ]
  pull_request:
    branches: [ "karsajobs" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x .//karsajobs/build_push_image_karsajobs.sh
         .//karsajobs/build_push_image_karsajobs.sh
      shell: bash
