apiVersion: v1
kind: Service
metadata:
  name: mytodo-app
  labels:
    app: mytodo-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    #nodePort: 30007
  selector:
    app: mytodo-app
