apiVersion: v1
kind: Service
metadata:
  name: mytodo-app
  labels:
    app: mytodo-app
spec:
  #type: 
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 30007
  selector:
    app: mytodo-app
